name: Automatic Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP archive
        run: |
          zip -r analisador-comissoes-linx-${{ github.ref_name }}.zip .next public package.json README.md LICENSE
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Analisador de Comissões Linx ${{ github.ref_name }}
          body: |
            ## Analisador de Comissões Linx ${{ github.ref_name }}
            
            ### 📋 Changelog
            
            ${{ steps.changelog.outputs.changelog }}
            
            ### 📦 Instalação
            
            ```bash
            # Clone o repositório
            git clone https://github.com/${{ github.repository }}.git
            
            # Entre no diretório
            cd $(basename ${{ github.repository }})
            
            # Instale as dependências
            npm install
            
            # Inicie o aplicativo
            npm run dev
            ```
            
            ### 📝 Notas da Versão
            
            Esta versão foi gerada automaticamente pelo GitHub Actions.
            
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
          files: |
            analisador-comissoes-linx-${{ github.ref_name }}.zip